POST http://localhost:3000/api/register
Content-Type: application/json
Accept: application/json

{
  "username": "www",
  "email": "wwww@example.com",
  "password": "password123",
  "role": "user"
}

